//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace devTest_Web.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiStorage
    {
        public int Id { get; set; }
        public string ApiData { get; set; }
    }
}
